# Generated by Django 3.0.6 on 2020-05-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('text', models.CharField(default='', max_length=300)),
                ('img_url', models.CharField(default='', max_length=500)),
                ('rezervace', models.BooleanField(default=False)),
            ],
        ),
    ]
